---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-app-fastapi.fullname" . }}-cm
  labels:
    {{- include "web-app-fastapi.labels" . | nindent 4 }}
data:
    ENVIRONMENT: {{ .Values.environment }}
