environment_secret: ENC[AES256_GCM,data:433VdbyeuPWopWc=,iv:vGSbbVxrZsg6ELcSnzX7XJHdsxN9Ewkq+AMc1KMnEgI=,tag:UNg4wNoExJoUls+FILM8sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-13T13:11:48Z"
    mac: ENC[AES256_GCM,data:Uvif6vwzy+PnF9yZgooRGWM/kFjt0Pc17rpisKalrf5uDUqye/4iX4QGAJfOA2aBAOkR0TcT13DAwsTIBNf1nnl4geHvbhDb377idtOI5Gr7wcw4tOX9JlROuOHmMm0YNEw7HYBVeh112ap9CMOBbXETvdCucaA23biC74VIN5k=,iv:o+gQN9cjcpuBEH3m7opJPil+bn6MAE9U6hcYl/fBkvA=,tag:ND+Hk7knOu/Z6lm4qEYcAQ==,type:str]
    pgp:
        - created_at: "2023-11-13T13:11:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8BgQQmjbNkKAQ//b35vZ7I20uduqSI/kioq6H5qBAJ2TGSVSvR5nA4lx7Rw
            Ohune73lMIQ91rCm6TY/XGLy3vI2FN69KhHbGSJjGN3PYKO/OXiLNhAT/LIPLlI/
            D2Q2RrlfHzHUlD0O441MYQqDngVbzjAhfULliuxASwgehoowieJUz6uv13da8bFx
            wKHjZQRZJrO7ZxS/VpLLZqWyCt3I9tZSn/7wnDE9CtrqvpGPO3wLCUOcxSxk9jxe
            RWYEATlrbs6sAfE5veJLc9Krik5ZSlaJTYKdVdWJ6HQZOPCg1C5Ff0K/3au2UP32
            KDwlxVA2sZ8gFcf6mzukxHp2nFdKDYMMwxqI7z5qpf12e/V46ierVRD8syyLw/pf
            7QL6Qr3raCYMLuZhcdRGfsjgzBi3jYCLyy9US3xLSmHYDfBDzs9FH7HxLZcikzF7
            tneU5hRKfbDnEn5TyxLLfjSiUyfLozEVu++qx6G1djAt0Liol04IZRYVRXO0vLc+
            0uQbbRDMOc9OcIuB+fgZrrUDqiCthG07bIhiENMLgK5HeLBdLrNHwaB/zLwT8L9l
            wVHq30QaJDgQYtl3FOo67y8mAEgBIPc3BeNugpUfoJa3eNmGnvZoFZHwAueJ/99f
            +S/CmUnDx1D2g/GbiwUswXrm3UKv+QAbyVtkVmokG5N/SDs6yT/5zbPHYxsOEajS
            XgGm6sZWaCwL0Bw5yDlhr1w+5AkqArxM1GPSHpVUNmEzaOKz/FDHPgsYJOO1Ay4o
            5Uem1VxXgC6qn9APUCf1AVcahs+Gai5Ji3npxexe7naZf0er8MYArsIZzQQbF6Y=
            =C1H9
            -----END PGP MESSAGE-----
          fp: 815ABA7781ED93F9F76E0DD16E21F643295B1458
    unencrypted_suffix: _unencrypted
    version: 3.8.1
